### ISSUE TITLE
Error: `AttributeError: module 'wandb.sdk.lib' has no attribute 'git'`

### ISSUE THREAD

**Issue by cdelavegamartin** [captain-pool/hydra-wandb-sweeper#8]
When trying to run a sweep with the plugin, I get the following error:
```
$ train_rnn -m +experiment=test_hydra_wandb_sweep_integration
Traceback (most recent call last):
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra_plugins/hydra_wandb_sweeper/wandb_sweeper.py", line 16, in __init__
    _impl = import_module("hydra_plugins.hydra_wandb_sweeper._impl")
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra_plugins/hydra_wandb_sweeper/_impl.py", line 104, in <module>
    wandb.sdk.lib.git.GitRepo.__init__ = _my_gitrepo_init
AttributeError: module 'wandb.sdk.lib' has no attribute 'git'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/carlos/.conda/envs/physmodjax/bin/train_rnn", line 33, in <module>
    sys.exit(load_entry_point('physmodjax', 'console_scripts', 'train_rnn')())
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 153, in multirun
    sweeper = Plugins.instance().instantiate_sweeper(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/core/plugins.py", line 138, in instantiate_sweeper
    sweeper = self._instantiate(config.hydra.sweeper)
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/core/plugins.py", line 112, in _instantiate
    plugin = instantiate(config=config, _target_=clazz)
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/carlos/.conda/envs/physmodjax/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'hydra_plugins.hydra_wandb_sweeper.wandb_sweeper.WandbSweeper':
AttributeError("module 'wandb.sdk.lib' has no attribute 'git'")
full_key: hydra.sweeper
```
I had a look, and it seems that `wandb.sdk.lib.git` was renamed to `wandb.sdk.lib.gitlib` in  [this pull request](https://github.com/wandb/wandb/pull/5437)

**Comment by psFournier** [comment]
Hello, 
I have the exact same problem. Did you find a fix ? I tried changing the names as you indicated but i got :
```
`
[2023-12-15 14:27:29,568][HYDRA] WandbSweeper(method=bayes, num_agents=2, count=3, budget=4, entity=None, project=hydra_plugin_test_project, name=hydra_plugin_test)
[2023-12-15 14:27:29,568][HYDRA] with parameterization {'experiment.db': {'distribution': 'categorical', 'values': ['mnist', 'cifar']}, 'experiment.lr': {'distribution': 'q_log_uniform', 'min': 0.02, 'max': 1.0, 'q': 2.0}, 'model.dropout': {'distribution': 'uniform', 'min': 0.0, 'max': 1.0}, 'experiment.batch_size': {'distribution': 'int_uniform', 'min': 4, 'max': 16}}
[2023-12-15 14:27:29,569][HYDRA] Sweep output dir: /d/pfournie/hydra-wandb-sweeper/example/multirun/2023-12-15/14-27-29
Traceback (most recent call last):
  File "my_app.py", line 100, in <module>
    app()
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/d/pfournie/hydra-wandb-sweeper/hydra_plugins/hydra_wandb_sweeper/wandb_sweeper.py", line 32, in sweep
    return self.sweeper.sweep(arguments)
  File "/d/pfournie/hydra-wandb-sweeper/hydra_plugins/hydra_wandb_sweeper/_impl.py", line 535, in sweep
    self.sweep_id = wandb.sweep(
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_sweep.py", line 108, in sweep
    wandb_login._login(_silent=True)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 277, in _login
    wlogin.setup(kwargs)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_login.py", line 111, in setup
    _logger = wandb.setup()._get_logger()
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 108, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 138, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1768, in _infer_run_settings_from_environment
    root = repo.root or os.getcwd()
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/lib/gitlib.py", line 86, in root
    if not self.repo:
  File "/d/pfournie/hydra-wandb-sweeper/venv/lib/python3.8/site-packages/wandb/sdk/lib/gitlib.py", line 64, in repo
    if not self._repo_initialized:
AttributeError: 'GitRepo' object has no attribute '_repo_initialized'

```
Thank you !
